### ISSUE TITLE
Installation of Dependency Packages Fails Everytime

### ISSUE THREAD

**Issue by amanharitsh123** [sugarlabs/rpi23-gen-image#14]
In every attempt to build the image , one or more of the required dependency package fail to download and the script  terminates with the error . Is there anything wrong with the APT Server i have been using ?
Should I select some regional mirror rather than http://ftp.debian.org/debian/

Logs Here : https://paste.fedoraproject.org/paste/7enpIZqlqvHLYxIPQjDsYg

**Comment by Hrishi1999** [comment]
Paste your deboostrap.log too, found in images...folder.

**Comment by Rishabh42** [comment]
Which OS have you been using?

**Comment by amanharitsh123** [comment]
Host : Ubuntu 16.04 
Schroot : Debian Stretch

**Comment by amanharitsh123** [comment]
[debootstrap.log](https://github.com/sugarlabs/rpi23-gen-image/files/1695890/debootstrap.log)

[Logs.txt](https://github.com/sugarlabs/rpi23-gen-image/files/1695897/Logs.txt)

**Comment by quozl** [comment]
In your https://paste.fedoraproject.org/paste/7enpIZqlqvHLYxIPQjDsYg ...
> W: Couldn't download package libgconf-2-4 (ver 3.2.6-4+b1 arch armhf)

Per https://packages.debian.org/search?keywords=libgconf-2-4 this version number is correct and is available from the Debian archives.

In your Logs.txt ...
> W: Couldn't download package cgmanager (ver 0.41-2 arch armhf)

Per https://packages.debian.org/search?keywords=cgmanager this version number is correct and is available from the Debian archives.

You've got a broken package archive *or* a broken network.

Nothing to do with rpi23-gen-image, so I'll close.

Use a different package archive, use a VPN to escape your broken network, or set up a local instance of `approx` and keep trying until `approx` has all packages cached.

**Comment by amanharitsh123** [comment]
Thank you for the suggestion, using the  local instance of approx solved my issue

**Comment by quozl** [comment]
That's great.  You should also work with your network provider to find out what the cause is.  If it happens with `debootstrap` it may also sometimes happen with `approx`, just that `approx` will let you retry only the downloads that failed.  Or change provider.  :grinning:  Some Sugar Labs members have used their shell account with `ssh -D` to set up a temporary SOCKS proxy; a VPN for HTTP{,S}.
