### ISSUE TITLE
Script crashes at 'make: *** No rule to make target 'firmware_install'.  Stop.' on Debian 9.4

### ISSUE THREAD

**Issue by Rishabh42** [sugarlabs/rpi23-gen-image#19]
Logs:

  INSTALL sound/usb/snd-usb-audio.ko
  INSTALL sound/usb/snd-usbmidi-lib.ko
  DEPMOD  4.14.72-v7
make: Leaving directory '/home/rishabh/rpi23-gen-image/images/stretch/build/chroot/usr/src/linux'
+ make -C /home/rishabh/rpi23-gen-image/images/stretch/build/chroot/usr/src/linux ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- INSTALL_FW_PATH=../../../lib firmware_install
make: Entering directory '/home/rishabh/rpi23-gen-image/images/stretch/build/chroot/usr/src/linux'
make: *** No rule to make target 'firmware_install'.  Stop.
make: Leaving directory '/home/rishabh/rpi23-gen-image/images/stretch/build/chroot/usr/src/linux'
+ cleanup
+ set +x
killing processes using mount point ...
removing temporary mount points ...

**Comment by amanharitsh123** [comment]
I am also facing this problem while building for arm kernel .Build for
arm64 and you will be fine.

I think we should report this issue to the upstream as well.

**Comment by quozl** [comment]
Probably no need to report, as upstream handled this already; please keep abreast of upstream issues, pull requests, and commits.

**Comment by Rishabh42** [comment]
Solved by PR #20
