### ISSUE TITLE
ALSA mixer not being recognised by Sugar

### ISSUE THREAD

**Issue by Rishabh42** [sugarlabs/rpi23-gen-image#4]
alsamixer is crucial for some activities like Measure and  turtleblocks to work properly, on typing 'alsamixer' in the Terminal activity, the following error is displayed:
$ alsamixer
cannot open mixer: No such file or directory
even though packages like alsa-utils and alsamixergui are installed.

**Comment by quozl** [comment]
Some of the kernel modules are not loaded in memory.  Loading is usually automatic by the kernel, but may have been done manually on Raspbian.  You can check the list of modules loaded using `sudo lsmod`.  One of the kernel modules is responsible for offering the device node for mixer.  You might diagnose this further by booting Raspbian and comparing `lsmod` between Raspbian and Debian.

Also review the `bootstrap.d/15-rpi-config.sh` file which adds `files/modules/raspi-blacklist.conf` to `/etc/modprobe.d/raspi-blacklist.conf` on the build.  It is not clear to me why these modules are blocked from loading.  Perhaps you will discover why.

**Comment by amanharitsh123** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=7663#p93439
Here is a fix suggested by jbeale (second comment) 
and i am collecting the lsmod output for both sugar and raspbian ,
i will provide them soon

**Comment by quozl** [comment]
The link from 2012?  Extremely improbable.  Please don't provide that output.  In my reply above I'm not asking for the output, or offering to diagnose, but rather pointing out the tools that should be used to diagnose.  As Raspbian audio works, and Sugar can be installed on Raspbian, everything needed is easily obtained, just that something has been missed from @Rishabh42's build.

**Comment by amanharitsh123** [comment]
@quozl i think , even this link from 2012 correctly sugests the module which might be a cause of problem ,as i am not defining any output now so it would not  be irrelevant to accept this as a solution, i will soon comment the test results for the fix i am currently thinking off and a Pull Request

**Comment by quozl** [comment]
Still think it is improbable; after all, that link was talking about module missing, and the module is not missing from your build, and is loaded automatically, according to your gist https://gist.github.com/amanharitsh123/85c055197ec91a26eec68d764ca187cf

Anyway, I don't think this is a sugarlabs/rpi23-gen-image problem; everything works on Raspbian, and nothing obvious has been done [in this fork](https://github.com/sugarlabs/rpi23-gen-image/commit/4cbdd7c5eae7d3300de2208898d68c993e5e79eb) to disable sound, so it must be a drtyhlpr/rpi23-gen-image problem.  Reproduce it upstream and work with them.

**Comment by amanharitsh123** [comment]
ENABLE_SOUND=true  has enabled the module . alsamixer can now detect the pulseaudio card , but still i cant get any output

**Comment by quozl** [comment]
@amanharitsh123 wrote:
> ENABLE_SOUND=true has enabled the module . alsamixer can now detect the
> pulseaudio card , but still i cant get any output

Which method are you using to test?  The `speaker-test` program is minimal and lowest level, using ALSA layer directly.

Which output are you testing; 3.5mm or HDMI?  Has `raspi-config` been used to configure the output?  See also https://www.raspberrypi.org/documentation/configuration/audio-config.md

**Comment by amanharitsh123** [comment]
@quozl  I deleted that comment because , the issue was again appreaded after reboot ,  please review the PR that i have made now :)

**Comment by quozl** [comment]
https://github.com/sugarlabs/rpi23-gen-image/commit/62db2d66cb2c4067583a65485b883226351730ac
